export const participantsObject = [
  {
    id: 1,
    name: 'Thuany Vilas Boas',
    role: 'Diretora Criação e Arte',
    company: 'AG. FLUMA',
  },
  {
    id: 2,
    name: 'Bruna Areco',
    role: 'Analista Comercial',
    company: 'AG. FLUMA',
  },
  {
    id: 3,
    name: 'Myrella Moura',
    role: 'Gerente de Operações',
    company: 'AG. FLUMA',
  },
  {
    id: 4,
    name: 'Max Gabriel',
    role: 'Assessor de Influenciadores',
    company: 'AG. FLUMA',
  },
  {
    id: 5,
    name: 'Jéssica Caroline',
    role: 'Analista de Operações',
    company: 'AG. FLUMA',
  },
  { id: 6, name: 'Ericlis Ortiz', role: 'Designer', company: 'AG. FLUMA' },
  {
    id: 7,
    name: 'Marcele Freire',
    role: 'Assistente Comercial',
    company: 'AG. FLUMA',
  },
  {
    id: 8,
    name: 'Ayren Campos',
    role: 'Assistente Comercial',
    company: 'AG. FLUMA',
  },
  {
    id: 9,
    name: 'Thiago Inacio',
    role: 'Produtor Audio Visual',
    company: 'AG. FLUMA',
  },
  {
    id: 10,
    name: 'Pedro Henrique Guedes',
    role: 'Assistente de Operações',
    company: 'AG. FLUMA',
  },
  {
    id: 11,
    name: 'Igor Gonzales',
    role: 'Analista Comercial',
    company: 'AG. FLUMA',
  },
  {
    id: 12,
    name: 'Bruna Luiza',
    role: 'Assistente de Operações',
    company: 'AG. FLUMA',
  },
  {
    id: 13,
    name: 'Matheus Jansen',
    role: 'Editor de Video',
    company: 'AG. FLUMA',
  },
  {
    id: 14,
    name: 'Anna Clara Belém',
    role: 'Social Media',
    company: 'AG. FLUMA',
  },
  {
    id: 15,
    name: 'Patricia Miranda',
    role: 'Serviços Gerais',
    company: 'AG. FLUMA',
  },
  {
    id: 16,
    name: 'Carla Souza',
    role: 'Assistente Administrativa',
    company: 'AG. FLUMA',
  },
  {
    id: 17,
    name: 'Bianca Portella',
    role: 'Assessora Lucas Tylty',
    company: 'GRUPO OTG',
  },
  { id: 18, name: 'Vanessa de Araujo', role: 'COO', company: 'GRUPO OTG' },
  {
    id: 19,
    name: 'Gabriela Alexandre',
    role: 'Supervisora de Marketing',
    company: 'GRUPO OTG',
  },
  {
    id: 20,
    name: 'Daniel Hiyoshiro',
    role: 'Gerente de Tráfego',
    company: 'GRUPO OTG',
  },
  { id: 21, name: 'Alessandro Godoy', role: 'CFO', company: 'GRUPO OTG' },
  {
    id: 22,
    name: 'Irene Gomes',
    role: 'Analista de CRM',
    company: 'GRUPO OTG',
  },
  {
    id: 23,
    name: 'Nathan Basualdo',
    role: 'Diretor de Arte',
    company: 'GRUPO OTG',
  },
  {
    id: 24,
    name: 'Tamiris de Oliveira',
    role: 'Social Media Assistente',
    company: 'GRUPO OTG',
  },
  {
    id: 25,
    name: 'Danilo Mendes',
    role: 'Especialista em Contingência',
    company: 'GRUPO OTG',
  },
  {
    id: 26,
    name: 'Bruna Maciel',
    role: 'Supervisora de Tecnologia',
    company: 'GRUPO OTG',
  },
  {
    id: 27,
    name: 'Lauriene da Cruz',
    role: 'Serviços Gerais',
    company: 'GRUPO OTG',
  },
  {
    id: 28,
    name: 'Vinicius Xavier',
    role: 'Analista de Auditoria',
    company: 'GRUPO OTG',
  },
  {
    id: 29,
    name: 'Victor Rodrigues',
    role: 'Assessor Rafuxo',
    company: 'GRUPO OTG',
  },
  {
    id: 30,
    name: 'Suele de Fatima',
    role: 'Serviços Gerais',
    company: 'GRUPO OTG',
  },
  {
    id: 31,
    name: 'Otávio Leal',
    role: 'Engenheiro de Dados',
    company: 'GRUPO OTG',
  },
  {
    id: 32,
    name: 'Renata Aparecida',
    role: 'Analista Financeiro',
    company: 'GRUPO OTG',
  },
  {
    id: 33,
    name: 'Iris Novais',
    role: 'Manutenção Predial',
    company: 'GRUPO OTG',
  },
  {
    id: 34,
    name: 'Éric Marcellus',
    role: 'Gestor de Tráfego Pago',
    company: 'GRUPO OTG',
  },
  {
    id: 35,
    name: 'Eliene Felix',
    role: 'Serviços Gerais',
    company: 'GRUPO OTG',
  },
  {
    id: 36,
    name: 'Paulo Cesar',
    role: 'Analista Financeiro',
    company: 'GRUPO OTG',
  },
  {
    id: 37,
    name: 'Mayara de Souza',
    role: 'Analista de Compras',
    company: 'GRUPO OTG',
  },
  {
    id: 38,
    name: 'Hevellyn Nicolly',
    role: 'Recepcionista',
    company: 'GRUPO OTG',
  },
  {
    id: 39,
    name: 'Joao Vitor de Souza',
    role: 'Analista de Banco de Dados',
    company: 'GRUPO OTG',
  },
  {
    id: 40,
    name: 'Adriana Rodrigues',
    role: 'Serviços Gerais',
    company: 'GRUPO OTG',
  },
  {
    id: 41,
    name: 'Lucas Bastos',
    role: 'Assessor Executivo',
    company: 'GRUPO OTG',
  },
  {
    id: 42,
    name: 'Carla de Oliveira',
    role: 'Analista de Tráfego',
    company: 'GRUPO OTG',
  },
  {
    id: 43,
    name: 'Pedro Cardoso',
    role: 'Desenvolvedor Full-Stack',
    company: 'GRUPO OTG',
  },
  {
    id: 44,
    name: 'Vitor Nunes de Souza',
    role: 'Gestor de Tráfego Pago',
    company: 'GRUPO OTG',
  },
  {
    id: 45,
    name: 'Laura Cristina',
    role: 'Serviços Gerais',
    company: 'GRUPO OTG',
  },
  {
    id: 46,
    name: 'Jhady Lorrane',
    role: 'Recepcionista',
    company: 'GRUPO OTG',
  },
  {
    id: 47,
    name: 'Vinicius Alexandre',
    role: 'Assistente de Tecnologia',
    company: 'GRUPO OTG',
  },
  { id: 48, name: 'Anderson Alencar', role: 'Motorista', company: 'GRUPO OTG' },
  {
    id: 49,
    name: 'Murillo Alexsander',
    role: 'Gestor de Tráfego Pago',
    company: 'GRUPO OTG',
  },
  {
    id: 50,
    name: 'André Lucas',
    role: 'Gestor de Contingência',
    company: 'GRUPO OTG',
  },
  {
    id: 51,
    name: 'Francielle Dias',
    role: 'Assistente de DP',
    company: 'GRUPO OTG',
  },
  {
    id: 52,
    name: 'Laiana Gomes',
    role: 'Supervisora de Compras',
    company: 'GRUPO OTG',
  },
  {
    id: 53,
    name: 'Rafaela Zain',
    role: 'Analista de DP',
    company: 'GRUPO OTG',
  },
  {
    id: 54,
    name: 'Luiz Felipe Drumond',
    role: 'Gerente Financeiro',
    company: 'GRUPO OTG',
  },
  {
    id: 55,
    name: 'Leonardo Matheus',
    role: 'Social Media',
    company: 'GRUPO OTG',
  },
  {
    id: 56,
    name: 'Vinicius Prebil',
    role: 'Supervisor Executivo',
    company: 'OTG COMUNICAÇÕES',
  },
  {
    id: 57,
    name: 'Lucas Mendes',
    role: 'Redator',
    company: 'OTG COMUNICAÇÕES',
  },
  {
    id: 58,
    name: 'Hellen Fernanda',
    role: 'Social Media',
    company: 'OTG COMUNICAÇÕES',
  },
  {
    id: 59,
    name: 'Leonardo Henrique',
    role: 'Social Media',
    company: 'OTG COMUNICAÇÕES',
  },
  {
    id: 60,
    name: 'Thaynara Godinho',
    role: 'Redatora',
    company: 'OTG COMUNICAÇÕES',
  },
  {
    id: 61,
    name: 'Cauê Matos Moraes',
    role: 'Host',
    company: 'OTG COMUNICAÇÕES',
  },
  {
    id: 62,
    name: 'Leandro Eduardo',
    role: 'Social Media',
    company: 'OTG COMUNICAÇÕES',
  },
  {
    id: 63,
    name: 'Erick Stephan',
    role: 'Designer Analista',
    company: 'OTG COMUNICAÇÕES',
  },
  {
    id: 64,
    name: 'Camilly de Oliveira',
    role: 'Analista Comercial',
    company: 'OTG COMUNICAÇÕES',
  },
  { id: 65, name: 'Cadu Cathoud', role: 'CEO', company: 'OTG VENTURES' },
  { id: 66, name: 'Felipe Chuquer', role: 'CRO', company: 'OTG VENTURES' },
  {
    id: 67,
    name: 'Agatha Suyane',
    role: 'Gestora de Pautas',
    company: 'OTG VENTURES',
  },
  { id: 68, name: 'Lucas Morais', role: 'Redator', company: 'OTG VENTURES' },
  {
    id: 69,
    name: 'José Carlos Xavier',
    role: 'Designer Analista',
    company: 'OTG VENTURES',
  },
  {
    id: 70,
    name: 'Rebeca Catarine',
    role: 'Social Media',
    company: 'OTG VENTURES',
  },
  {
    id: 71,
    name: 'Junior Abranches',
    role: 'Gerente de Tecnologia',
    company: 'OTG VENTURES',
  },
  {
    id: 72,
    name: 'Ederson Ceolin',
    role: 'Assistente de PO',
    company: 'OTG VENTURES',
  },
  {
    id: 73,
    name: 'Thamiris Machado',
    role: 'Assistente de Atendimento',
    company: 'OTG VENTURES',
  },
  {
    id: 74,
    name: 'Matheus Queiroz',
    role: 'Analista de Comunicação',
    company: 'OTG VENTURES',
  },
  {
    id: 75,
    name: 'Jobson Brito',
    role: 'Web Designer',
    company: 'OTG VENTURES',
  },
  {
    id: 76,
    name: 'Luilyan de Oliveira',
    role: 'Assistente de Redação',
    company: 'OTG VENTURES',
  },
  {
    id: 77,
    name: 'Jhordan Williams',
    role: 'Assistente de Operações',
    company: 'OTG VENTURES',
  },
  {
    id: 78,
    name: 'Jose Felipe',
    role: 'Analista de Operações',
    company: 'OTG VENTURES',
  },
  {
    id: 79,
    name: 'Ana Clara Martins',
    role: 'Supervisora de Criação',
    company: 'OTG VENTURES',
  },
  { id: 80, name: 'Miguel Panza', role: 'Redator', company: 'OTG VENTURES' },
  {
    id: 81,
    name: 'Vitor Soares',
    role: 'Produtor Audiovisual',
    company: 'OTG VENTURES',
  },
  { id: 82, name: 'Douglas Paco', role: 'Designer', company: 'OTG VENTURES' },
  {
    id: 83,
    name: 'Rodrigo Campiotto',
    role: 'Jornalista Esportivo',
    company: 'OTG VENTURES',
  },
  {
    id: 84,
    name: 'Luiz Fernando',
    role: 'Analista Comercial',
    company: 'OTG VENTURES',
  },
  {
    id: 85,
    name: 'Gustavo Henrique',
    role: 'Analista Comercial',
    company: 'OTG VENTURES',
  },
  {
    id: 86,
    name: 'Amanda Ceolin',
    role: 'Assistente de Projetos',
    company: 'OTG VENTURES',
  },
  {
    id: 87,
    name: 'Rodrygo Vieira',
    role: 'Assistente de PO',
    company: 'OTG VENTURES',
  },
  {
    id: 88,
    name: 'Bárbara Carvalho',
    role: 'Assistente de Atendimento',
    company: 'OTG VENTURES',
  },
  {
    id: 89,
    name: 'Rafaella Samla',
    role: 'Assistente de Atendimento',
    company: 'OTG VENTURES',
  },
  {
    id: 90,
    name: 'José Henrique',
    role: 'Gestor de Pautas',
    company: 'OTG VENTURES',
  },
  {
    id: 91,
    name: 'Afonso Machado',
    role: 'Desenvolvedor',
    company: 'OTG VENTURES',
  },
  {
    id: 92,
    name: 'Gabriel Faustino',
    role: 'Desenvolvedor',
    company: 'OTG VENTURES',
  },
  {
    id: 93,
    name: 'Hellita Kamila',
    role: 'Scrum Master',
    company: 'OTG VENTURES',
  },
  {
    id: 94,
    name: 'Leonardo Amaral',
    role: 'Desenvolvedor',
    company: 'OTG VENTURES',
  },
  {
    id: 95,
    name: 'Marianne Vitoria',
    role: 'Analista de Q.A',
    company: 'OTG VENTURES',
  },
  {
    id: 96,
    name: 'Julia de Freitas',
    role: 'Copywriter',
    company: 'OTG VENTURES',
  },
  {
    id: 97,
    name: 'Vinicius Boldrin',
    role: 'Web Designer',
    company: 'OTG VENTURES',
  },
  {
    id: 98,
    name: 'Igor Stringhini',
    role: 'Assistente de BI',
    company: 'OTG VENTURES',
  },
  {
    id: 99,
    name: 'Leilaine de Rezende',
    role: 'Redatora',
    company: 'OTG VENTURES',
  },
  { id: 100, name: 'Sofia Júlia', role: 'UX/UI', company: 'OTG VENTURES' },
  {
    id: 101,
    name: 'Rodrigo Monteiro',
    role: 'Analista QA',
    company: 'OTG VENTURES',
  },
  {
    id: 102,
    name: 'Kaio Fabiano',
    role: 'Desenvolvedor',
    company: 'OTG VENTURES',
  },
  {
    id: 103,
    name: 'Mattheus Vargas',
    role: 'Brand Designer',
    company: 'OTG VENTURES',
  },
  {
    id: 104,
    name: 'Pedro Henrique',
    role: 'Assistente de Envio de Operações',
    company: 'TYLTY COMPANY',
  },
  {
    id: 105,
    name: 'Matheus Vogl',
    role: 'Analista de Relacionamento',
    company: 'TYLTY COMPANY',
  },
  {
    id: 106,
    name: 'Lucia Portella',
    role: 'Assistente Virtual',
    company: 'TYLTY COMPANY',
  },
  {
    id: 107,
    name: 'Lívia Beatriz',
    role: 'Head Gol do Rayo e Vitor ZZ',
    company: 'TYLTY COMPANY',
  },
  {
    id: 108,
    name: 'Marllon Santos',
    role: 'Gerente Executivo',
    company: 'TYLTY COMPANY',
  },
  {
    id: 109,
    name: 'Alisson Telles',
    role: 'Analista de Controle',
    company: 'TYLTY COMPANY',
  },
  {
    id: 110,
    name: 'Lucas de Aguiar',
    role: 'Head Barack, DG, Nathan e Thierry',
    company: 'TYLTY COMPANY',
  },
  {
    id: 111,
    name: 'Matheus Soares',
    role: 'Designer',
    company: 'TYLTY COMPANY',
  },
  {
    id: 112,
    name: 'Vitor Douglas',
    role: 'Assistente Operacional',
    company: 'TYLTY COMPANY',
  },
  {
    id: 113,
    name: 'Breno Lacerda',
    role: 'Assistente de Projetos',
    company: 'TYLTY COMPANY',
  },
  {
    id: 114,
    name: 'Felipe Colen',
    role: 'Assistente de Envio de Operações',
    company: 'TYLTY COMPANY',
  },
  {
    id: 115,
    name: 'Nathalia Patricia',
    role: 'Gestora de Pautas',
    company: 'TYLTY COMPANY',
  },
  {
    id: 116,
    name: 'Karine Alves',
    role: 'Assistente de Atendimento',
    company: 'TYLTY COMPANY',
  },
  {
    id: 117,
    name: 'Luiz Guilherme',
    role: 'Supervisor de Operações',
    company: 'TYLTY COMPANY',
  },
  {
    id: 118,
    name: 'Tainan Paim',
    role: 'Assistente de Atendimento',
    company: 'TYLTY COMPANY',
  },
  {
    id: 119,
    name: 'Diego Pacheco',
    role: 'Gerente de Marketing',
    company: 'TYLTY COMPANY',
  },
  {
    id: 120,
    name: 'Diogo Carvalho',
    role: 'Assistente de Informações',
    company: 'TYLTY COMPANY',
  },
  {
    id: 121,
    name: 'Leandro de Aquino',
    role: 'Designer',
    company: 'TYLTY COMPANY',
  },
  {
    id: 122,
    name: 'João Vittor Barbosa',
    role: 'Analista de Projetos',
    company: 'TYLTY COMPANY',
  },
  {
    id: 123,
    name: 'Gislany Bezerra',
    role: 'Assistente Virtual',
    company: 'TYLTY COMPANY',
  },
  {
    id: 124,
    name: 'Marcell Rondon',
    role: 'Supervisor de Comunicação',
    company: 'TYLTY COMPANY',
  },
  {
    id: 125,
    name: 'Marcos Cunha',
    role: 'Gerente de Operações',
    company: 'TYLTY COMPANY',
  },
  {
    id: 126,
    name: 'Yohen Emiliano',
    role: 'Envio de Operações',
    company: 'TYLTY COMPANY',
  },
  {
    id: 127,
    name: 'Joás Junior',
    role: 'Administrador Camarote',
    company: 'TYLTY COMPANY',
  },
  {
    id: 128,
    name: 'Scarlet Ohana',
    role: 'Social Media',
    company: 'TYLTY COMPANY',
  },
  {
    id: 129,
    name: 'Jorge dos Santos',
    role: 'Designer',
    company: 'TYLTY COMPANY',
  },
  {
    id: 130,
    name: 'Cleuziane Marques',
    role: 'Assistente de Atendimento',
    company: 'TYLTY COMPANY',
  },
  {
    id: 131,
    name: 'Davi Sacramento',
    role: 'Assistente de Atendimento',
    company: 'TYLTY COMPANY',
  },
  {
    id: 132,
    name: 'Nathan Fernandes',
    role: 'Assistente Operacional',
    company: 'TYLTY COMPANY',
  },
  {
    id: 133,
    name: 'Lucas Gimenes',
    role: 'Analista de Projetos',
    company: 'TYLTY COMPANY',
  },
  {
    id: 134,
    name: 'Eduardo Gonçalves',
    role: 'Editor de Videos',
    company: 'TYLTY COMPANY',
  },
  {
    id: 135,
    name: 'Vinicius Grawe',
    role: 'Editor de Video',
    company: 'OTG VENTURES',
  },
  {
    id: 136,
    name: 'Edson Júnior',
    role: 'Analista de Projetos',
    company: 'TYLTY COMPANY',
  },
  {
    id: 137,
    name: 'Iago Dionisio',
    role: 'Analista de Projetos',
    company: 'TYLTY COMPANY',
  },
  {
    id: 138,
    name: 'Lucas Percine',
    role: 'Analista de Projetos',
    company: 'TYLTY COMPANY',
  },
  {
    id: 139,
    name: 'Paula Melo de Luna',
    role: 'Analista de Marketing',
    company: 'TYLTY COMPANY',
  },
  {
    id: 140,
    name: 'Victor Vilela',
    role: 'Editor de Videos',
    company: 'TYLTY COMPANY',
  },
  {
    id: 141,
    name: 'Matheus Velozo',
    role: 'Social Media Analista',
    company: 'TYLTY COMPANY',
  },
  {
    id: 142,
    name: 'Rafael Araujo',
    role: 'Designer Analista',
    company: 'TYLTY COMPANY',
  },
  {
    id: 143,
    name: 'Alexandre de Miranda',
    role: 'Analista de Projetos',
    company: 'TYLTY COMPANY',
  },
  {
    id: 144,
    name: 'Hedymaura Zanon',
    role: 'Assistente de Operações',
    company: 'TYLTY COMPANY',
  },
  {
    id: 145,
    name: 'Daniel Martins',
    role: 'Editor de Videos',
    company: 'TYLTY COMPANY',
  },
  {
    id: 146,
    name: 'Wagner Fernandes',
    role: 'Head Ana Green, LF Telles e Rennan',
    company: 'TYLTY COMPANY',
  },
  {
    id: 147,
    name: 'Gean dos Santos',
    role: 'Editor de Videos',
    company: 'TYLTY COMPANY',
  },
  {
    id: 148,
    name: 'Yasmin Gabrielly',
    role: 'Redator',
    company: 'TYLTY COMPANY',
  },
  {
    id: 149,
    name: 'Carlos Wendryl',
    role: 'Head Barba, Emílio e Vozdi Galinha',
    company: 'TYLTY COMPANY',
  },
  {
    id: 150,
    name: 'Joao Carlos Kohlhase',
    role: 'Gestor de Pautas',
    company: 'TYLTY COMPANY',
  },
  {
    id: 151,
    name: 'Gabriel dos Santos',
    role: 'Assistente Operacional',
    company: 'TYLTY COMPANY',
  },
  {
    id: 152,
    name: 'João Martins',
    role: 'Copywritter',
    company: 'TYLTY COMPANY',
  },
  {
    id: 153,
    name: 'Henrique Oliva',
    role: 'Analista de Relacionamento',
    company: 'TYLTY COMPANY',
  },
  {
    id: 154,
    name: 'Luiza Fonseca',
    role: 'Analista de Relacionamento',
    company: 'TYLTY COMPANY',
  },
  {
    id: 155,
    name: 'Hercilio Da Silva',
    role: 'Motion Designer',
    company: 'TYLTY COMPANY',
  },
  {
    id: 156,
    name: 'Gabriel Moraes',
    role: 'Motion Designer',
    company: 'TYLTY COMPANY',
  },
  {
    id: 157,
    name: 'João Queiroz',
    role: 'Assistente de Contas',
    company: 'TYLTY COMPANY',
  },
  {
    id: 158,
    name: 'Ana Beatriz Lopes',
    role: 'Assistente Administrativa',
    company: 'TYLTY COMPANY',
  },
  {
    id: 159,
    name: 'Gabriel Badan',
    role: 'Head Fábio Guilherme e Thaís Herculano',
    company: 'TYLTY COMPANY',
  },
  {
    id: 160,
    name: 'Larissa Silva',
    role: 'Redatora',
    company: 'TYLTY COMPANY',
  },
  {
    id: 161,
    name: 'Denisson Neto',
    role: 'Assistente de Contas',
    company: 'TYLTY COMPANY',
  },
  {
    id: 162,
    name: 'Lucas Correa',
    role: 'Assistente Virtual',
    company: 'TYLTY COMPANY',
  },
  {
    id: 163,
    name: 'Cezar Rodrigues',
    role: 'Editor de Vídeo',
    company: 'TYLTY COMPANY',
  },
  {
    id: 164,
    name: 'Gabriel Cabral',
    role: 'Videomaker - Editor',
    company: 'TYLTY COMPANY',
  },
  {
    id: 165,
    name: 'Lucas Pitangui',
    role: 'Copywriting',
    company: 'TYLTY COMPANY',
  },
  {
    id: 166,
    name: 'Joelson Fernandes',
    role: 'Segurança',
    company: 'GRUPO OTG',
  },
  {
    id: 167,
    name: 'Maria Lady Neves',
    role: 'Serviços Gerais',
    company: 'GRUPO OTG',
  },
]
